name: Build test with MSVC
on:
  workflow_call:

  # 手動トリガーを許可
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: MSVC-BuildTest
          max-size: "200M"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore Nuget Packages
        run: |
          NuGet restore .\Hengband\Hengband.sln

      - name: Print sccache path
        run: |
          (Get-Command sccache).Source

      - name: copy sccache.exe as cl.exe to temporary directory
        run: |
          Copy-Item -v -Path (Get-Command sccache).Source -Destination $env:TEMP\cl.exe -Force

      - name: Run build test
        run: |
          MSBuild -warnAsError .\Hengband\Hengband.sln /p:CLToolPath=$env:TEMP /p:CLToolExe=cl.exe /t:Rebuild /p:Configuration=Debug
